### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by CitizenDev** [mietzen/docker-redsocks-proxy#7]
Can you please modify redsocks-proxy to Handle Proxy Authentication:

Update the redsocks.conf.template to include PROXY_USER and PROXY_PASSWORD.
Adjust the entrypoint.sh to substitute these variables.

**Comment by mietzen** [comment]
Here you go #8

**Comment by mietzen** [comment]
Change are Released in the latest [stable](https://hub.docker.com/layers/mietzen/redsocks-proxy/stable/images/sha256-65d3993de62cabb1bb758ed41dd57ce63b2834f964f6ecaf3eef8df02c0691dc?context=explore) image

**Comment by mietzen** [comment]
I only set it up to tunnel Port 80 and 443, but redsocks is limited to TCP traffic, I think the easiest way would be to run something like https://dnscrypt.info/ on the docker host and set the DNS Server to: `dns: 127.0.0.1:53`

**Comment by mietzen** [comment]
@CitizenDev played around with DNSCrypt:

https://github.com/mietzen/docker-redsocks-proxy/tree/dnscrypt 

It's just an example, you can test it with:

```
git clone https://github.com/mietzen/docker-redsocks-proxy.git
cd docker-redsocks-proxy
git switch dnscrypt
docker compose up --build
```

It will tunnel all TCP traffic and catch all UDP DNS requests and redirect them to DNSCrypt / Quad9 DoH via the SOCKS5 Proxy.
